obj/EquipmentOverlays
	BlankVisoredMask
		icon='BlankVisoredMask.dmi'
		layer=6;pixel_y=9
	DANKVisoredMask
		icon='DANKVisoredMask.dmi'
		layer=6;pixel_y=9
	HornedVisoredMask
		icon='HornedVisoredMask.dmi'
		layer=6;pixel_y=9